### ISSUE TITLE
Collection Month

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/metadata-for-user-facility-template-transformations#28]
Collection Month should ONLY be the month for JGI templates. Also, JGI captures the month as a text, the month written out... so for 2021-05-21 ... 05 needs to be May in the JGI template.

Take the NMDC slot collection_date and parse out the pieces so ONLY month is in this column of the JGI export. And correct to be text
01= January
02= February
03= March 
 etc.

**Comment by mslarae13** [comment]
It now shows just the month https://github.com/microbiomedata/metadata-template-transformation/commit/5d0886613f2cab2e94d106d487c95becd89f8d3c

But as a number.

Needs to be the written month

**Comment by sujaypatil96** [comment]
This has been fixed in https://github.com/microbiomedata/metadata-for-user-facility-template-transformations/commit/90dd5b5db7a9093fd9f82c4de684da7387727870, issue can be closed.

**Comment by mslarae13** [comment]
LGTM

**Comment by mslarae13** [comment]
@cristina-stonepedraza this is closed but can you take a look at it?
I think it's still broken in the jgi_mt one.

**Comment by cristina-stonepedraza** [comment]
Fixed in 38bc221
